//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverythingCmdPal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverythingCmdPal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set clipboard content, another program may have control.
        /// </summary>
        internal static string clipboard_failed {
            get {
                return ResourceManager.GetString("clipboard_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open context menu for:.
        /// </summary>
        internal static string context_failed {
            get {
                return ResourceManager.GetString("context_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open context menu.
        /// </summary>
        internal static string context_menu {
            get {
                return ResourceManager.GetString("context_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File/Folder copied to clipboard..
        /// </summary>
        internal static string copy_ok {
            get {
                return ResourceManager.GetString("copy_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path.
        /// </summary>
        internal static string copy_path {
            get {
                return ResourceManager.GetString("copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path copied to clipboard..
        /// </summary>
        internal static string copy_path_ok {
            get {
                return ResourceManager.GetString("copy_path_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete:.
        /// </summary>
        internal static string delete_confirm {
            get {
                return ResourceManager.GetString("delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will be deleted without being sent to recycling bin.
        ///This action will be irreversible..
        /// </summary>
        internal static string delete_warn {
            get {
                return ResourceManager.GetString("delete_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure Everything is running?.
        /// </summary>
        internal static string everything_not_running {
            get {
                return ResourceManager.GetString("everything_not_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything exe.
        /// </summary>
        internal static string exe {
            get {
                return ResourceManager.GetString("exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of Everything executable file.
        ///Used for &quot;Show more&quot; option..
        /// </summary>
        internal static string exe_description {
            get {
                return ResourceManager.GetString("exe_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string file_not_found {
            get {
                return ResourceManager.GetString("file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filters.toml.
        /// </summary>
        internal static string filter_path {
            get {
                return ResourceManager.GetString("filter_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder containing the customized filters.toml.
        ///If filters.toml does not exist in this folder, the default template will be applied..
        /// </summary>
        internal static string filter_path_description {
            get {
                return ResourceManager.GetString("filter_path_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match path.
        /// </summary>
        internal static string match_path {
            get {
                return ResourceManager.GetString("match_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search path in additional to file/folder name..
        /// </summary>
        internal static string match_path_description {
            get {
                return ResourceManager.GetString("match_path_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum amount of results to display in the results..
        /// </summary>
        internal static string max_description {
            get {
                return ResourceManager.GetString("max_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing here to search with Everything.
        /// </summary>
        internal static string noquery {
            get {
                return ResourceManager.GetString("noquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in console.
        /// </summary>
        internal static string open_console {
            get {
                return ResourceManager.GetString("open_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to open console..
        /// </summary>
        internal static string open_console_exception {
            get {
                return ResourceManager.GetString("open_console_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open:.
        /// </summary>
        internal static string open_exception {
            get {
                return ResourceManager.GetString("open_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        internal static string open_file {
            get {
                return ResourceManager.GetString("open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string open_folder {
            get {
                return ResourceManager.GetString("open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open properties.
        /// </summary>
        internal static string open_properties {
            get {
                return ResourceManager.GetString("open_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with.
        /// </summary>
        internal static string open_with {
            get {
                return ResourceManager.GetString("open_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query prefix.
        /// </summary>
        internal static string prefix {
            get {
                return ResourceManager.GetString("prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds prefix to all queries, so that you can always include certain filters/modifiers without typing it every time.
        ///Space is not added automatically between prefix and query..
        /// </summary>
        internal static string prefix_description {
            get {
                return ResourceManager.GetString("prefix_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEx.
        /// </summary>
        internal static string regex {
            get {
                return ResourceManager.GetString("regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable regular expression in search.
        ///Recommend using regex: in query instead of enabling this option..
        /// </summary>
        internal static string regex_description {
            get {
                return ResourceManager.GetString("regex_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as admin.
        /// </summary>
        internal static string run_admin {
            get {
                return ResourceManager.GetString("run_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute as admin.
        /// </summary>
        internal static string run_admin_exception {
            get {
                return ResourceManager.GetString("run_admin_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as user.
        /// </summary>
        internal static string run_as {
            get {
                return ResourceManager.GetString("run_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Run as user.
        /// </summary>
        internal static string run_as_description {
            get {
                return ResourceManager.GetString("run_as_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute as user.
        /// </summary>
        internal static string run_as_exception {
            get {
                return ResourceManager.GetString("run_as_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to specified.
        /// </summary>
        internal static string sendto {
            get {
                return ResourceManager.GetString("sendto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send selected result to the specified program.
        ///Separate program path and argument with comma (,) where $P$ represents the path of the selected result..
        /// </summary>
        internal static string sendto_description {
            get {
                return ResourceManager.GetString("sendto_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Send to.
        /// </summary>
        internal static string sendto_enable {
            get {
                return ResourceManager.GetString("sendto_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set whether the send to option needs to be displayed..
        /// </summary>
        internal static string sendto_enable_description {
            get {
                return ResourceManager.GetString("sendto_enable_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send to:.
        /// </summary>
        internal static string sendto_failed {
            get {
                return ResourceManager.GetString("sendto_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        internal static string show_more {
            get {
                return ResourceManager.GetString("show_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a result that opens Everything with the current query..
        /// </summary>
        internal static string show_more_description {
            get {
                return ResourceManager.GetString("show_more_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show query results in Everything main window..
        /// </summary>
        internal static string show_more_subtitle {
            get {
                return ResourceManager.GetString("show_more_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string sort {
            get {
                return ResourceManager.GetString("sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set result sorting method..
        /// </summary>
        internal static string sort_description {
            get {
                return ResourceManager.GetString("sort_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly find files and folders with Everything.
        /// </summary>
        internal static string top_level_subtitle {
            get {
                return ResourceManager.GetString("top_level_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string unknown_error {
            get {
                return ResourceManager.GetString("unknown_error", resourceCulture);
            }
        }
    }
}
