//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverythingCmdPal3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverythingCmdPal3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set clipboard content, another program may have control.
        /// </summary>
        public static string clipboard_failed {
            get {
                return ResourceManager.GetString("clipboard_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path.
        /// </summary>
        public static string copy_path {
            get {
                return ResourceManager.GetString("copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path copied to clipboard.
        /// </summary>
        public static string copy_path_ok {
            get {
                return ResourceManager.GetString("copy_path_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        public static string date_mod {
            get {
                return ResourceManager.GetString("date_mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete:.
        /// </summary>
        public static string delete_confirm {
            get {
                return ResourceManager.GetString("delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will be deleted without being sent to recycling bin
        ///This action will be irreversible.
        /// </summary>
        public static string delete_warn {
            get {
                return ResourceManager.GetString("delete_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string ERROR_UNKNOWN {
            get {
                return ResourceManager.GetString("ERROR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request.
        /// </summary>
        public static string EVERYTHING3_ERROR_BAD_REQUEST {
            get {
                return ResourceManager.GetString("EVERYTHING3_ERROR_BAD_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad server response.
        /// </summary>
        public static string EVERYTHING3_ERROR_BAD_RESPONSE {
            get {
                return ResourceManager.GetString("EVERYTHING3_ERROR_BAD_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cancelled the query.
        /// </summary>
        public static string EVERYTHING3_ERROR_CANCELLED {
            get {
                return ResourceManager.GetString("EVERYTHING3_ERROR_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from pipe server.
        /// </summary>
        public static string EVERYTHING3_ERROR_DISCONNECTED {
            get {
                return ResourceManager.GetString("EVERYTHING3_ERROR_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough room to store response data.
        /// </summary>
        public static string EVERYTHING3_ERROR_INSUFFICIENT_BUFFER {
            get {
                return ResourceManager.GetString("EVERYTHING3_ERROR_INSUFFICIENT_BUFFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command.
        /// </summary>
        public static string EVERYTHING3_ERROR_INVALID_COMMAND {
            get {
                return ResourceManager.GetString("EVERYTHING3_ERROR_INVALID_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter.
        /// </summary>
        public static string EVERYTHING3_ERROR_INVALID_PARAMETER {
            get {
                return ResourceManager.GetString("EVERYTHING3_ERROR_INVALID_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property value type is incorrect.
        /// </summary>
        public static string EVERYTHING3_ERROR_INVALID_PROPERTY_VALUE_TYPE {
            get {
                return ResourceManager.GetString("EVERYTHING3_ERROR_INVALID_PROPERTY_VALUE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPC is not available
        ///(Everything search client is not running).
        /// </summary>
        public static string EVERYTHING3_ERROR_IPC_PIPE_NOT_FOUND {
            get {
                return ResourceManager.GetString("EVERYTHING3_ERROR_IPC_PIPE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to allocate memory for the search query.
        /// </summary>
        public static string EVERYTHING3_ERROR_OUT_OF_MEMORY {
            get {
                return ResourceManager.GetString("EVERYTHING3_ERROR_OUT_OF_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property not found.
        /// </summary>
        public static string EVERYTHING3_ERROR_PROPERTY_NOT_FOUND {
            get {
                return ResourceManager.GetString("EVERYTHING3_ERROR_PROPERTY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error (server out of memory).
        /// </summary>
        public static string EVERYTHING3_ERROR_SERVER {
            get {
                return ResourceManager.GetString("EVERYTHING3_ERROR_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown initiated by user.
        /// </summary>
        public static string EVERYTHING3_ERROR_SHUTDOWN {
            get {
                return ResourceManager.GetString("EVERYTHING3_ERROR_SHUTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation completed successfully.
        /// </summary>
        public static string EVERYTHING3_OK {
            get {
                return ResourceManager.GetString("EVERYTHING3_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything exe.
        /// </summary>
        public static string exe {
            get {
                return ResourceManager.GetString("exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of Everything executable file
        ///Used for &quot;Show more&quot; option.
        /// </summary>
        public static string exe_description {
            get {
                return ResourceManager.GetString("exe_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string ext {
            get {
                return ResourceManager.GetString("ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string file_not_found {
            get {
                return ResourceManager.GetString("file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Name.
        /// </summary>
        public static string instance {
            get {
                return ResourceManager.GetString("instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the instance to connect to
        ///If you&apos;re unsure, leave blank or try 1.5a.
        /// </summary>
        public static string instance_description {
            get {
                return ResourceManager.GetString("instance_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Everything.
        /// </summary>
        public static string launch_e {
            get {
                return ResourceManager.GetString("launch_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match path.
        /// </summary>
        public static string match_path {
            get {
                return ResourceManager.GetString("match_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search path in additional to file/folder name.
        /// </summary>
        public static string match_path_description {
            get {
                return ResourceManager.GetString("match_path_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum amount of results to display in the results.
        /// </summary>
        public static string max_description {
            get {
                return ResourceManager.GetString("max_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in console.
        /// </summary>
        public static string open_console {
            get {
                return ResourceManager.GetString("open_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to open console.
        /// </summary>
        public static string open_console_exception {
            get {
                return ResourceManager.GetString("open_console_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open:.
        /// </summary>
        public static string open_exception {
            get {
                return ResourceManager.GetString("open_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string open_file {
            get {
                return ResourceManager.GetString("open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string open_folder {
            get {
                return ResourceManager.GetString("open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with.
        /// </summary>
        public static string open_with {
            get {
                return ResourceManager.GetString("open_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query prefix.
        /// </summary>
        public static string prefix {
            get {
                return ResourceManager.GetString("prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds prefix to all queries, so that you can always include certain filters/modifiers without typing it every time
        ///Space is not added automatically between prefix and query.
        /// </summary>
        public static string prefix_description {
            get {
                return ResourceManager.GetString("prefix_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEx.
        /// </summary>
        public static string regex {
            get {
                return ResourceManager.GetString("regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable regular expression in search
        ///Recommend using regex: in query instead of enabling this option.
        /// </summary>
        public static string regex_description {
            get {
                return ResourceManager.GetString("regex_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as admin.
        /// </summary>
        public static string run_admin {
            get {
                return ResourceManager.GetString("run_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute as admin.
        /// </summary>
        public static string run_admin_exception {
            get {
                return ResourceManager.GetString("run_admin_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as user.
        /// </summary>
        public static string run_as {
            get {
                return ResourceManager.GetString("run_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Run as user.
        /// </summary>
        public static string run_as_description {
            get {
                return ResourceManager.GetString("run_as_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute as user.
        /// </summary>
        public static string run_as_exception {
            get {
                return ResourceManager.GetString("run_as_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to specified.
        /// </summary>
        public static string sendto {
            get {
                return ResourceManager.GetString("sendto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send selected result to the specified program
        ///Separate program path and argument with comma (,) where $P$ represents the path of the selected result.
        /// </summary>
        public static string sendto_description {
            get {
                return ResourceManager.GetString("sendto_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Send to.
        /// </summary>
        public static string sendto_enable {
            get {
                return ResourceManager.GetString("sendto_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set whether the send to option needs to be displayed.
        /// </summary>
        public static string sendto_enable_description {
            get {
                return ResourceManager.GetString("sendto_enable_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send to:.
        /// </summary>
        public static string sendto_failed {
            get {
                return ResourceManager.GetString("sendto_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More.
        /// </summary>
        public static string show_more {
            get {
                return ResourceManager.GetString("show_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a result that opens Everything with the current query.
        /// </summary>
        public static string show_more_description {
            get {
                return ResourceManager.GetString("show_more_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show query results in Everything main window.
        /// </summary>
        public static string show_more_subtitle {
            get {
                return ResourceManager.GetString("show_more_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string sort {
            get {
                return ResourceManager.GetString("sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Ascending.
        /// </summary>
        public static string sort_ascending {
            get {
                return ResourceManager.GetString("sort_ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort ascending.
        /// </summary>
        public static string sort_ascending_description {
            get {
                return ResourceManager.GetString("sort_ascending_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set result sorting method.
        /// </summary>
        public static string sort_description {
            get {
                return ResourceManager.GetString("sort_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly find files and folders with Everything.
        /// </summary>
        public static string top_level_subtitle {
            get {
                return ResourceManager.GetString("top_level_subtitle", resourceCulture);
            }
        }
    }
}
